In [ ]:
import numpy as np
import pandas as pd
from prophet import Prophet
import warnings
warnings.filterwarnings('ignore')
import itertools
import pyodbc
# from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_percentage_error as smape
from dotenv.main import load_dotenv
import os

In [2]:
server = '10.3.4.139,1433'
database = 'dwh_prod'
username = 'developerptba'
password = 'LnfPYVFW1K2TAKf'

In [5]:
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()
query = "SELECT * FROM dwh.DM_financial_position_unpivot;"
df = pd.read_sql(query, cnxn)
df

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
0,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Actual,3.376864e+09,2023-01-31 05:11:01,2025-03-05 07:45:11.143
1,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,RKAP,2.840146e+09,2023-01-31 05:11:01,2025-03-05 07:45:11.143
2,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Optimize,0.000000e+00,2023-01-31 05:11:01,2025-03-05 07:45:11.143
3,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Moderate,0.000000e+00,2023-01-31 05:11:01,2025-03-05 07:45:11.143
4,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Worst,0.000000e+00,2023-01-31 05:11:01,2025-03-05 07:45:11.143
...,...,...,...,...,...,...,...,...,...,...,...,...
49407,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,RKAP,1.844921e+10,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49408,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Optimize,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49409,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Moderate,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49410,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Worst,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49411,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Projection,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177

In [ ]:
# df = pd.read_csv("D:/PT Bukit Asam/Document 2024/Script Python/DM_financial_position_unpivot_full.csv")

In [6]:
df

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
0,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Actual,3.376864e+09,2023-01-31 05:11:01,2025-03-05 07:45:11.143
1,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,RKAP,2.840146e+09,2023-01-31 05:11:01,2025-03-05 07:45:11.143
2,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Optimize,0.000000e+00,2023-01-31 05:11:01,2025-03-05 07:45:11.143
3,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Moderate,0.000000e+00,2023-01-31 05:11:01,2025-03-05 07:45:11.143
4,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,Worst,0.000000e+00,2023-01-31 05:11:01,2025-03-05 07:45:11.143
...,...,...,...,...,...,...,...,...,...,...,...,...
49407,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,RKAP,1.844921e+10,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49408,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Optimize,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49409,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Moderate,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49410,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Worst,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49411,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,Projection,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177

In [7]:
df['BreakDown'].unique()

array(['Fuel Usage of Marketing', 'Other Selling Expenses of Marketing',
       'Cash Conversion Cycle', 'Salaries, Wages, and Employee Benefits',
       'Total Current Assets', 'Accured Expenses',
       'EBITDA After Minority', "Payment to stockholders' loan",
       'Cash from/(used in) Investing Activities', 'Cash Currency GBP',
       'Cash Currency USD', 'Payment from debt', 'USDIDR AVG',
       'Inventory Turnover', 'Others of Non Current Assets',
       'Non Current Portion of Interest Bearing Debt',
       'Receipt of tax refund', 'Revenue Derti', 'IPC Production',
       'Net Debt to EBITDA', 'Total Export Sales of Coal',
       'Balance Stock UPTE Live Stock', 'Business Travel and Education',
       'Dividen Receipt from Subsidiaries/Associate/JVCo.',
       'Ending Cash Balance', 'EBITDA Margin',
       'EBITDA to Interest Coverage Ratio', 'Operating Profit Margin',
       'Return on Equity',
       'Purchases of available-for-sale financial assets', 'NCI',
       'Coal Realized Price', 'Beginning Cash Balance',
       'Payments for mining properties/deferred development expenditure',
       'Cost of Revenue', 'Cash and Deposit', 'Account Payables',
       'Other Income', 'Placement of reclamationand mine closure funds',
       'Depreciation and Amortization of COGM',
       'Ratio Net Profit After Minority', 'Retribution of Marketing',
       'Operating Profit/(Loss)', 'Total Transport',
       'Sales Volume Domestic Industri Semen',
       'Balance Stock UPTE Temporary', 'Cash inflow from Customers',
       'Cash Outflow to Supplier & Employee', 'Total Production',
       'Rent of GA', 'Sales Volume Domestic PLN', 'Cash Currency EUR',
       'Total Equity', 'AR Turnover', 'AP Turnover',
       'Total Current Liabilities',
       'Additional of financial assests at fair value through other comprehensive income',
       'Withdrawal of (placement on) performance bonds',
       'Average Export Price', 'Depreciation and Amortization of GA',
       'Total Stockpile', 'Inventories', 'Routine',
       'Cash and Cash Equivalents', 'Average Market Price USD',
       'Net Profit/(Loss)', 'Payment from published new stocks', 'EBITDA',
       '(Placement)/Withdrawal of time deposit', 'Others Payment/Receipt',
       'Ore Mining Fees', 'Rent of COGM', 'USDIDR End Of Month',
       'Average Domestic Price', 'Total Non Current Assets',
       'Royalties, Taxes, and Other Retribution',
       'Cash from/(used in) Operating Activities', 'Debt to Equity Ratio',
       'Payment from bank loan', 'Other Stockpile', 'SR',
       'Royalties and Other Retribution', 'Dividend Payment',
       'Loan bank payment', 'Rent Payment Received',
       'Gross Profit Margin', 'Office Supplies', 'UPTE Production',
       'Investment/divestment in Fixed Assets', 'Cash Currency JPY',
       'Cash Currency SGD', 'Transportation', 'Debt payment',
       'Others of Current Assets', 'Revenue Peltar',
       'Total Domestic Sales of Coal', 'Debt to EBITDA',
       'Net Profit Margin', 'Peranap Production', 'TE Stockpile',
       'Exchange Rate Effect', 'Current Ratio',
       'Payment from stockholders loan', 'Payment to stockholders loan',
       'Revenue UPTE', 'Coal Cash Cost',
       'Total Sales & Marketing Expense', 'BAP', 'Tax',
       'Land and Building Tax', 'Total Revenue',
       'Finished Goods Adjustment', 'Fuel Usage', 'Spareparts Used',
       "Dividend payment to company's owners", 'Treasury stock purchase',
       'Cash from/(used in) Financing Activities', 'Subsidiaries',
       'Total Liabilities', 'Selling Price Domestic Lainnya',
       'Account Receivables', 'Rent Payment', 'Fixed Assets', 'Demurrage',
       'Depreciation and Amortization of Marketing',
       'Payments for plantation', 'Interest Payment', 'BANKO',
       'Taxes Payable', 'Third Party Service', 'Tax & Royalti Payment',
       'Return on Asset', 'Investment in Joint Venture Entities',
       'Retribution of GA', 'Total General & Administrative Expense',
       'Dividend payment to companys owners',
       'Salaries, Wages, Bonuses and Employee Benefits of Marketing',
       'Current Portion of Interest Bearing Debt', 'UPO Production',
       'Sales Volume Domestic Lainnya', 'Cash Currency IDR',
       'Cash Increase/(Decrease)', 'Cash Currency AUD',
       'Fuel Usage of GA', 'Average Market Price IDR',
       'Other Administrative Expenses', 'Other Revenue',
       'Others of Non Current Liabilities', 'Interest Receipt',
       'Corporate Social Responsibility Program', 'KPT Transport',
       'Selling Price Domestic PLN',
       'Investment in Subsidiaries/Associate/JVCo.',
       'Salaries, Wages, Bonuses and Employee Benefits of GA', 'MTB',
       'Net Profit After Minority', 'TRH Stockpile', 'TRH Transport',
       'Obligation Received', 'Total Operating Expenses',
       'Others of COGM', 'Deposit', 'Others of Current Liabilities',
       'Gross Profit/(Loss)', 'KPT Stockpile', 'Total Qty of Coal Sales',
       'Proceeds from disposal of available-for-sale financial assets',
       'Total Assets', 'Acquisition of associates', 'Despatch',
       'Total Non Current Liabilities', 'TAL',
       'Sales Volume Domestic Industri Pupuk',
       "Payment from stockholders' loan", 'Other Expense', 'Coal Revenue',
       'Development', 'Shipping and Insurance of Marketing',
       'Transportation and Ore Mining Fees', 'Revenue Peranap',
       'Revenue IPC'], dtype=object)

In [8]:
df_SALES = df[df['BreakDown'].isin(['Total Domestic Sales of Coal','Total Export Sales of Coal'])].copy()
df_SALES

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
119,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,Sri Lanka,None,Actual,0.00,2023-01-31 05:11:01,2025-03-05 07:45:11.050
120,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,Sri Lanka,None,RKAP,0.00,2023-01-31 05:11:01,2025-03-05 07:45:11.050
121,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,Sri Lanka,None,Optimize,0.00,2023-01-31 05:11:01,2025-03-05 07:45:11.050
122,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,Sri Lanka,None,Moderate,0.00,2023-01-31 05:11:01,2025-03-05 07:45:11.050
123,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,Sri Lanka,None,Worst,0.00,2023-01-31 05:11:01,2025-03-05 07:45:11.050
...,...,...,...,...,...,...,...,...,...,...,...,...
49335,2024-08-31,8,2024,Total Export Sales,Total Export Sales of Coal,None,China,None,Amount_USD,10340280.91,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49336,2024-08-31,8,2024,Total Export Sales,Total Export Sales of Coal,None,China,None,Weight,144708.09,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49337,2024-08-31,8,2024,Total Export Sales,Total Export Sales of Coal,None,China,None,Load_TRH,77200.00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49338,2024-08-31,8,2024,Total Export Sales,Total Export Sales of Coal,None,China,None,Load_KPT,0.00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49339,2024-08-31,8,2024,Total Export Sales,Total Export Sales of Coal,None,China,None,Load_IPC,67508.09,2024-08-31 05:11:01,2025-03-05 07:45:11.177

In [9]:
# df_overview_actual : jenis : aktual
df_SALES_actual = df_SALES[df_SALES['tipe'] == "Actual"]

# data diurutkan dari awal data
df_SALES_date = df_SALES_actual.sort_values(by='Date')

df_SALES_group = df_SALES_date.groupby(['Date'])['amount'].sum().reset_index()
df_SALES_group

          Date      amount
0   2022-01-31  2091660.10
1   2022-02-28  2056355.83
2   2022-03-31  2818667.63
3   2022-04-30  2728947.26
4   2022-05-31  2654839.01
5   2022-06-30  2273833.86
6   2022-07-31  2605831.36
7   2022-08-31  2963096.08
8   2022-09-30  3312228.82
9   2022-10-31  2960079.20
10  2022-11-30  2505290.98
11  2022-12-31  2682803.66
12  2023-01-31  3043288.96
13  2023-02-28  3055737.30
14  2023-03-31  3352099.87
15  2023-04-30  2998080.14
16  2023-05-31  2511115.99
17  2023-06-30  3116288.53
18  2023-07-31  3293657.72
19  2023-08-31  3048437.67
20  2023-09-30  3233981.37
21  2023-10-31  3354324.99
22  2023-11-30  3213940.87
23  2023-12-31  3403811.56
24  2024-01-31  3363549.28
25  2024-02-29  3066871.59
26  2024-03-31  3216894.33
27  2024-04-30  3280380.33
28  2024-05-31  3633723.23
29  2024-06-30  3493225.60
30  2024-07-31  1763647.20
31  2024-08-31  3723244.55
32  2024-09-30  3717905.91
33  2024-10-31  3945523.85
34  2024-11-30  3813305.36
35  2024-12-31  3854621.78
36  2025-01-31  3123760.90

In [7]:
df_SALES_group.isna().sum()

Date      0
amount    0
dtype: int64

In [10]:
df_SALES_group.columns = ['ds','y']
df_SALES_group['ds'] = pd.to_datetime(df_SALES_group['ds'])

# Kombinasi parameter untuk tuning
changepoint_prior_scales = [0.01, 0.05,0.1]
seasonality_modes = ['additive']
seasonality_prior_scales = [0.01, 0.05, 1.0]

# Membuat list kombinasi parameter
param_combinations = list(itertools.product(changepoint_prior_scales, seasonality_modes, seasonality_prior_scales))

# Fungsi untuk menghitung SMAPE
def smape(actual, predicted):
    return 100 * np.mean(2 * np.abs(predicted - actual) / (np.abs(predicted) + np.abs(actual)))

# Menyimpan hasil tuning
best_smape = float('inf')
best_params = None

# Train dan test split
train_size = int(0.8 * len(df_SALES_group))
train_data = df_SALES_group[:train_size]
test_data = df_SALES_group[train_size:]

# Looping untuk setiap kombinasi parameter
for changepoint_prior_scale, seasonality_mode, seasonality_prior_scale in param_combinations:
    
    # Inisialisasi model Prophet dengan parameter tuning
    model = Prophet(
        yearly_seasonality=True, 
        weekly_seasonality=False, 
        daily_seasonality=False,
        changepoint_prior_scale=changepoint_prior_scale,
        seasonality_mode=seasonality_mode,
        seasonality_prior_scale=seasonality_prior_scale
    )
    model.add_seasonality(name='monthly', period=30.5, fourier_order=5)
    
    # Melatih model dengan data train
    model.fit(train_data)

    # Membuat dataframe masa depan yang mencakup periode data test
    future = model.make_future_dataframe(periods=len(test_data), freq='MS')

    # Melakukan prediksi
    forecast = model.predict(future)

    # Mengambil prediksi yang sesuai dengan data test
    forecast_test = forecast[-len(test_data):]

    # Menggabungkan data asli dengan prediksi
    test_data.loc[:, 'yhat'] = forecast_test['yhat'].values

    # Menghitung SMAPE untuk data test
    smape_value = smape(test_data['y'], test_data['yhat'])
    print(f"SMAPE dengan changepoint_prior_scale={changepoint_prior_scale}, seasonality_mode={seasonality_mode}, seasonality_prior_scale={seasonality_prior_scale}: {smape_value:.2f}%")

    # Menyimpan kombinasi parameter terbaik
    if smape_value < best_smape:
        best_smape = smape_value
        best_params = (changepoint_prior_scale, seasonality_mode, seasonality_prior_scale)

print(f"\nParameter terbaik: changepoint_prior_scale={best_params[0]}, seasonality_mode={best_params[1]}, seasonality_prior_scale={best_params[2]}")
print(f"SMAPE terbaik: {best_smape:.2f}%")

# Latih model dengan seluruh data menggunakan parameter terbaik
final_model = Prophet(
    yearly_seasonality=True, 
    weekly_seasonality=False, 
    daily_seasonality=False,
    changepoint_prior_scale=best_params[0],
    seasonality_mode=best_params[1],
    seasonality_prior_scale=best_params[2]
)
final_model.add_seasonality(name='monthly', period=30.5, fourier_order=5)

# Melatih model dengan seluruh data
final_model.fit(df_SALES_group)

# Membuat dataframe masa depan untuk 6 bulan ke depan
future = final_model.make_future_dataframe(periods=12, freq='MS')

# Melakukan prediksi
forecast_final = final_model.predict(future)

# Menampilkan hasil prediksi
# print(forecast_final[['ds', 'yhat', 'yhat_lower', 'yhat_upper']])

# Menyimpan hasil prediksi ke dalam DataFrame
forecast_df = forecast_final[['ds', 'yhat']]

07:46:08 - cmdstanpy - INFO - Chain [1] start processing
07:46:09 - cmdstanpy - INFO - Chain [1] done processing
07:46:09 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.01: 13.03%

07:46:09 - cmdstanpy - INFO - Chain [1] done processing
07:46:09 - cmdstanpy - INFO - Chain [1] start processing
07:46:10 - cmdstanpy - INFO - Chain [1] done processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.05: 12.20%

07:46:10 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=1.0: 56.35%

07:46:10 - cmdstanpy - INFO - Chain [1] done processing
07:46:10 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.05, seasonality_mode=additive, seasonality_prior_scale=0.01: 12.89%

07:46:10 - cmdstanpy - INFO - Chain [1] done processing
07:46:10 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.05, seasonality_mode=additive, seasonality_prior_scale=0.05: 12.20%

07:46:11 - cmdstanpy - INFO - Chain [1] done processing
07:46:11 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.05, seasonality_mode=additive, seasonality_prior_scale=1.0: 56.32%

07:46:11 - cmdstanpy - INFO - Chain [1] done processing
07:46:11 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.01: 12.99%

07:46:12 - cmdstanpy - INFO - Chain [1] done processing
07:46:12 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.05: 12.19%

07:46:32 - cmdstanpy - INFO - Chain [1] done processing
07:46:32 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=1.0: 87.97%

Parameter terbaik: changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.05
SMAPE terbaik: 12.19%

07:46:32 - cmdstanpy - INFO - Chain [1] done processing

In [11]:
forecast_df

           ds          yhat
0  2022-01-31  2.324474e+06
1  2022-02-28  2.389633e+06
2  2022-03-31  2.763748e+06
3  2022-04-30  2.656953e+06
4  2022-05-31  2.578058e+06
5  2022-06-30  2.604881e+06
6  2022-07-31  2.227871e+06
7  2022-08-31  2.867613e+06
8  2022-09-30  3.035381e+06
9  2022-10-31  3.022868e+06
10 2022-11-30  2.803587e+06
11 2022-12-31  2.923909e+06
12 2023-01-31  2.725681e+06
13 2023-02-28  2.760949e+06
14 2023-03-31  3.147429e+06
15 2023-04-30  3.021965e+06
16 2023-05-31  2.950391e+06
17 2023-06-30  2.967741e+06
18 2023-07-31  2.617458e+06
19 2023-08-31  3.260592e+06
20 2023-09-30  3.414897e+06
21 2023-10-31  3.409170e+06
22 2023-11-30  3.180049e+06
23 2023-12-31  3.312802e+06
24 2024-01-31  3.126928e+06
25 2024-02-29  3.084507e+06
26 2024-03-31  3.468427e+06
27 2024-04-30  3.363555e+06
28 2024-05-31  3.306141e+06
29 2024-06-30  3.317171e+06
30 2024-07-31  2.922652e+06
31 2024-08-31  3.586091e+06
32 2024-09-30  3.748455e+06
33 2024-10-31  3.754795e+06
34 2024-11-30  3.523837e+06
35 2024-12-31  3.651435e+06
36 2025-01-31  3.452520e+06
37 2025-02-01  3.379121e+06
38 2025-03-01  3.408957e+06
39 2025-04-01  3.787255e+06
40 2025-05-01  3.703189e+06
41 2025-06-01  3.661547e+06
42 2025-07-01  3.668760e+06
43 2025-08-01  3.231484e+06
44 2025-09-01  3.909972e+06
45 2025-10-01  4.079944e+06
46 2025-11-01  4.098804e+06
47 2025-12-01  3.868628e+06
48 2026-01-01  3.990857e+06

In [12]:
# Menyusun Data Frame Sales
forecast_rows = pd.DataFrame({
    'Date': forecast_df['ds'],
    'Tonase': forecast_df['yhat'],
    'Jenis': 'Forecast',
    'Breakdown' : 'Total Sales'
})

df_actual_sales = pd.DataFrame({
    'Date': df_SALES_group['ds'],
    'Tonase': df_SALES_group['y'],
    'Jenis': 'Actual',
    'Breakdown' : 'Total Sales'
})

# Menggabungkan semua DataFrame
result_df_Sales = pd.concat([df_actual_sales,forecast_rows ], ignore_index=True)
result_df_Sales

         Date        Tonase     Jenis    Breakdown
0  2022-01-31  2.091660e+06    Actual  Total Sales
1  2022-02-28  2.056356e+06    Actual  Total Sales
2  2022-03-31  2.818668e+06    Actual  Total Sales
3  2022-04-30  2.728947e+06    Actual  Total Sales
4  2022-05-31  2.654839e+06    Actual  Total Sales
..        ...           ...       ...          ...
81 2025-09-01  3.909972e+06  Forecast  Total Sales
82 2025-10-01  4.079944e+06  Forecast  Total Sales
83 2025-11-01  4.098804e+06  Forecast  Total Sales
84 2025-12-01  3.868628e+06  Forecast  Total Sales
85 2026-01-01  3.990857e+06  Forecast  Total Sales

[86 rows x 4 columns]

In [13]:
df_Sales_Ekspor = df_SALES_actual[df_SALES_actual['BreakDown']=='Total Export Sales of Coal']
df_Sales_Ekspor

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
119,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,Sri Lanka,None,Actual,0.0,2023-01-31 05:11:01,2025-03-05 07:45:11.050
142,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,Turkey,None,Actual,0.0,2023-01-31 05:11:01,2025-03-05 07:45:11.050
185,2024-04-30,4,2024,Total Export Sales,Total Export Sales of Coal,None,Bangladesh,None,Actual,0.0,2024-04-30 05:11:01,2025-03-05 07:45:11.177
262,2023-01-31,1,2023,Total Export Sales,Total Export Sales of Coal,None,England,None,Actual,0.0,2023-01-31 05:11:01,2025-03-05 07:45:11.050
272,2024-04-30,4,2024,Total Export Sales,Total Export Sales of Coal,None,Cambodia,None,Actual,0.0,2024-04-30 05:11:01,2025-03-05 07:45:11.177
...,...,...,...,...,...,...,...,...,...,...,...,...
49145,2024-07-31,7,2024,Total Export Sales,Total Export Sales of Coal,None,Cambodia,None,Actual,0.0,2024-07-31 05:11:01,2025-03-05 07:45:11.177
49175,2023-12-31,12,2023,Total Export Sales,Total Export Sales of Coal,None,Myanmar,None,Actual,0.0,2023-12-31 05:11:01,2025-03-05 07:45:11.160
49199,2023-12-31,12,2023,Total Export Sales,Total Export Sales of Coal,None,Singapore,None,Actual,0.0,2023-12-31 05:11:01,2025-03-05 07:45:11.160
49293,2024-07-31,7,2024,Total Export Sales,Total Export Sales of Coal,None,Sri Lanka,None,Actual,0.0,2024-07-31 05:11:01,2025-03-05 07:45:11.177
49329,2024-08-31,8,2024,Total Export Sales,Total Export Sales of Coal,None,China,None,Actual,0.0,2024-08-31 05:11:01,2025-03-05 07:45:11.177

In [14]:
df_Sales_Ekspor = df_Sales_Ekspor.sort_values(by='Date')

df_Sales_Ekspor = df_Sales_Ekspor.groupby(['Date'])['amount'].sum().reset_index()
df_Sales_Ekspor = df_Sales_Ekspor[df_Sales_Ekspor['amount']!= 0]
df_Sales_Ekspor

          Date      amount
0   2022-01-31   344709.49
1   2022-02-28   590855.99
2   2022-03-31  1350178.55
3   2022-04-30  1027221.48
4   2022-05-31  1025365.98
5   2022-06-30   824570.98
6   2022-07-31   934896.26
7   2022-08-31  1279021.74
8   2022-09-30  1664507.92
9   2022-10-31  1499129.00
10  2022-11-30   936233.00
11  2022-12-31  1004631.00
12  2023-01-31  1295215.06
13  2023-02-28  1302408.74
14  2023-03-31  1696676.18
15  2023-04-30  1423509.87
16  2023-05-31   761553.32
17  2023-06-30  1268254.65
18  2023-07-31  1538280.36
19  2023-08-31  1225539.00
20  2023-09-30  1385517.00
21  2023-10-31  1369382.00
22  2023-11-30  1298205.00
23  2023-12-31  1656267.00
24  2024-01-31  1087610.00
25  2024-02-29  1388715.00
26  2024-03-31  1314117.00
27  2024-04-30  1203206.00
28  2024-05-31  1865405.00
29  2024-06-30  1626103.00
31  2024-08-31  1968804.09
32  2024-09-30  1822722.91
33  2024-10-31  1996892.00
34  2024-11-30  2007731.00
35  2024-12-31  1956135.00
36  2025-01-31  1460425.00

In [15]:
df_Sales_Ekspor.columns = ['ds','y']
df_Sales_Ekspor['ds'] = pd.to_datetime(df_Sales_Ekspor['ds'])

# Kombinasi parameter untuk tuning
changepoint_prior_scales = [0.01, 0.05,0.1]
seasonality_modes = ['additive']
seasonality_prior_scales = [0.01, 0.05, 1.0]

# Membuat list kombinasi parameter
param_combinations = list(itertools.product(changepoint_prior_scales, seasonality_modes, seasonality_prior_scales))

# Fungsi untuk menghitung SMAPE
def smape(actual, predicted):
    return 100 * np.mean(2 * np.abs(predicted - actual) / (np.abs(predicted) + np.abs(actual)))

# Menyimpan hasil tuning
best_smape = float('inf')
best_params = None

# Train dan test split
train_size = int(0.8 * len(df_Sales_Ekspor))
train_data = df_Sales_Ekspor[:train_size]
test_data = df_Sales_Ekspor[train_size:]

# Looping untuk setiap kombinasi parameter
for changepoint_prior_scale, seasonality_mode, seasonality_prior_scale in param_combinations:
    
    # Inisialisasi model Prophet dengan parameter tuning
    model = Prophet(
        yearly_seasonality=True, 
        weekly_seasonality=True, 
        daily_seasonality=False,
        changepoint_prior_scale=changepoint_prior_scale,
        seasonality_mode=seasonality_mode,
        seasonality_prior_scale=seasonality_prior_scale,
        growth='linear'
    )
    model.add_seasonality(name='monthly', period=30, fourier_order=3)
    
    # Melatih model dengan data train
    model.fit(train_data)

    # Membuat dataframe masa depan yang mencakup periode data test
    future = model.make_future_dataframe(periods=len(test_data), freq='MS')

    # Melakukan prediksi
    forecast = model.predict(future)

    # Mengambil prediksi yang sesuai dengan data test
    forecast_test = forecast[-len(test_data):]

    # Menggabungkan data asli dengan prediksi
    test_data.loc[:, 'yhat'] = forecast_test['yhat'].values

    # Menghitung SMAPE untuk data test
    smape_value = smape(test_data['y'], test_data['yhat'])
    print(f"SMAPE dengan changepoint_prior_scale={changepoint_prior_scale}, seasonality_mode={seasonality_mode}, seasonality_prior_scale={seasonality_prior_scale}: {smape_value:.2f}%")

    # Menyimpan kombinasi parameter terbaik
    if smape_value < best_smape:
        best_smape = smape_value
        best_params = (changepoint_prior_scale, seasonality_mode, seasonality_prior_scale)

print(f"\nParameter terbaik: changepoint_prior_scale={best_params[0]}, seasonality_mode={best_params[1]}, seasonality_prior_scale={best_params[2]}")
print(f"SMAPE terbaik: {best_smape:.2f}%")

# Latih model dengan seluruh data menggunakan parameter terbaik
final_model = Prophet(
    yearly_seasonality=True, 
    weekly_seasonality=True, 
    daily_seasonality=False,
    changepoint_prior_scale=best_params[0],
    seasonality_mode=best_params[1],
    seasonality_prior_scale=best_params[2],
    growth='linear'
)
final_model.add_seasonality(name='monthly', period=30, fourier_order=3)

# Melatih model dengan seluruh data
final_model.fit(df_Sales_Ekspor)

# Membuat dataframe masa depan untuk 6 bulan ke depan
future = final_model.make_future_dataframe(periods=12, freq='MS')

# Melakukan prediksi
forecast_final = final_model.predict(future)

# Menampilkan hasil prediksi
# print(forecast_final[['ds', 'yhat', 'yhat_lower', 'yhat_upper']])

# Menyimpan hasil prediksi ke dalam DataFrame
forecast_df_sales_ekspor = forecast_final[['ds', 'yhat']]

07:46:51 - cmdstanpy - INFO - Chain [1] start processing
07:46:52 - cmdstanpy - INFO - Chain [1] done processing
07:46:52 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.01: 20.73%

07:46:52 - cmdstanpy - INFO - Chain [1] done processing
07:46:52 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.05: 26.20%

07:46:54 - cmdstanpy - INFO - Chain [1] done processing
07:46:54 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=1.0: 138.45%

07:46:54 - cmdstanpy - INFO - Chain [1] done processing
07:46:54 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.05, seasonality_mode=additive, seasonality_prior_scale=0.01: 20.39%

07:46:54 - cmdstanpy - INFO - Chain [1] done processing
07:46:54 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.05, seasonality_mode=additive, seasonality_prior_scale=0.05: 26.01%

07:46:58 - cmdstanpy - INFO - Chain [1] done processing
07:46:58 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.05, seasonality_mode=additive, seasonality_prior_scale=1.0: 173.99%

07:46:59 - cmdstanpy - INFO - Chain [1] done processing
07:46:59 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.01: 20.39%

07:46:59 - cmdstanpy - INFO - Chain [1] done processing
07:46:59 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.05: 26.00%

07:47:21 - cmdstanpy - INFO - Chain [1] done processing
07:47:21 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=1.0: 105.45%

Parameter terbaik: changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.01
SMAPE terbaik: 20.39%

07:47:21 - cmdstanpy - INFO - Chain [1] done processing

In [16]:
# # Menyimpan hasil prediksi ke dalam DataFrame
# forecast_df_sales_ekspor = forecast_final[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
# forecast_df_sales_ekspor.columns = ['Date', 'Forecast', 'Lower Bound', 'Upper Bound']

# # Membulatkan kolom Forecast, Lower Bound, dan Upper Bound ke dua angka di belakang koma
# forecast_df_sales_ekspor['Forecast'] = forecast_df_sales_ekspor['Forecast'].round(2)
# forecast_df_sales_ekspor['Lower Bound'] = forecast_df_sales_ekspor['Lower Bound'].round(2)
# forecast_df_sales_ekspor['Upper Bound'] = forecast_df_sales_ekspor['Upper Bound'].round(2)
# # --- Tambahan Akumulasi Forecast per Tahun ---
# # Menambahkan kolom tahun berdasarkan kolom 'Date'

# forecast_df_sales_ekspor['year'] = forecast_df_sales_ekspor['Date'].dt.year

# # Menghitung akumulasi kumulatif per tahun
# cumulative_forecast_yearly = forecast_df_sales_ekspor.groupby('year')[['Forecast', 'Lower Bound', 'Upper Bound']].cumsum()

# # Menyimpan hasil kumulatif ke dalam DataFrame baru
# cumulative_forecast_df_sales_ekspor_yearly = pd.DataFrame({
#     'Date': forecast_df_sales_ekspor['Date'],
#     'Year': forecast_df_sales_ekspor['year'],
#     'Cumulative Forecast': cumulative_forecast_yearly['Forecast'].round(2),
#     'Cumulative Lower Bound': cumulative_forecast_yearly['Lower Bound'].round(2),
#     'Cumulative Upper Bound': cumulative_forecast_yearly['Upper Bound'].round(2)
# })

# # Menampilkan DataFrame kumulatif hasil prediksi per tahun
# # print("\nData kumulatif forecast per tahun:")
# # print(cumulative_forecast_df_sales_ekspor_yearly)

# # Pastikan kolom 'Date' dalam format datetime
# forecast_df_sales_ekspor['Date'] = pd.to_datetime(forecast_df_sales_ekspor['Date'])
# Menambahkan data untuk 'Forecast'
forecast_rows_SE = pd.DataFrame({
    'Date': forecast_df_sales_ekspor['ds'],
    'Tonase': forecast_df_sales_ekspor['yhat'],
    'Jenis': 'Forecast',
    'Breakdown' : 'Total Sales Ekspor'
})

df_actual_sales_ekspor = pd.DataFrame({
    'Date': df_Sales_Ekspor['ds'],
    'Tonase': df_Sales_Ekspor['y'],
    'Jenis': 'Actual',
    'Breakdown' : 'Total Sales Ekspor'
})

# cumulative_forecast_rows_ekspor = pd.DataFrame({
#     'ds': cumulative_forecast_df_sales_ekspor_yearly['Date'],
#     'y': cumulative_forecast_df_sales_ekspor_yearly['Cumulative Forecast'],
#     'jenis': 'cumulative forecast',
#     'Breakdown': 'Total Sales Ekspor'
# })

# Menggabungkan semua DataFrame
result_df_Sales_Export = pd.concat([df_actual_sales_ekspor,forecast_rows_SE ], ignore_index=True)
result_df_Sales_Export

         Date        Tonase     Jenis           Breakdown
0  2022-01-31  3.447095e+05    Actual  Total Sales Ekspor
1  2022-02-28  5.908560e+05    Actual  Total Sales Ekspor
2  2022-03-31  1.350179e+06    Actual  Total Sales Ekspor
3  2022-04-30  1.027221e+06    Actual  Total Sales Ekspor
4  2022-05-31  1.025366e+06    Actual  Total Sales Ekspor
..        ...           ...       ...                 ...
79 2025-09-01  2.013334e+06  Forecast  Total Sales Ekspor
80 2025-10-01  2.044098e+06  Forecast  Total Sales Ekspor
81 2025-11-01  2.100759e+06  Forecast  Total Sales Ekspor
82 2025-12-01  2.075156e+06  Forecast  Total Sales Ekspor
83 2026-01-01  2.134602e+06  Forecast  Total Sales Ekspor

[84 rows x 4 columns]

-----

In [17]:
df_Sales_Domestic = df_SALES_actual[df_SALES_actual['BreakDown']=='Total Domestic Sales of Coal']
df_Sales_Domestic

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
719,2023-01-31,1,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1748073.90,2023-01-31 05:11:01,2025-03-05 07:45:11.050
1684,2024-04-30,4,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,2077174.33,2024-04-30 05:11:01,2025-03-05 07:45:11.177
3600,2022-05-31,5,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1629473.03,2022-05-31 05:11:01,2025-03-05 07:45:11.083
3953,2024-02-29,2,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1678156.59,2024-02-29 05:11:01,2025-03-05 07:45:11.160
9032,2024-01-31,1,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,2275939.28,2024-01-31 05:11:01,2025-03-05 07:45:11.160
9815,2023-03-31,3,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1655423.69,2023-03-31 05:11:01,2025-03-05 07:45:11.130
10956,2023-02-28,2,2023,Total Domestic Sales,Total Domestic Sales of Coal,Ton,None,None,Actual,1753328.56,2023-02-28 05:11:01,2025-03-05 07:45:11.130
12234,2024-03-31,3,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1902777.33,2024-03-31 05:11:01,2025-03-05 07:45:11.177
12730,2022-04-30,4,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1701725.78,2022-04-30 05:11:01,2025-03-05 07:45:11.083
13355,2022-07-31,7,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1670935.10,2022-07-31 05:11:01,2025-03-05 07:45:11.097
14120,2023-05-31,5,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1749562.67,2023-05-31 05:11:01,2025-03-05 07:45:11.130
15733,2022-03-31,3,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1468489.08,2022-03-31 05:11:01,2025-03-05 07:45:11.083
17391,2022-08-31,8,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1684074.34,2022-08-31 05:11:01,2025-03-05 07:45:11.097
18057,2023-10-31,10,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1984942.99,2023-10-31 05:11:01,2025-03-05 07:45:11.143
19198,2022-06-30,6,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1449262.88,2022-06-30 05:11:01,2025-03-05 07:45:11.083
22015,2023-08-31,8,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1822898.67,2023-08-31 05:11:01,2025-03-05 07:45:11.143
22350,2024-06-30,6,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1867122.60,2024-06-30 05:11:01,2025-03-05 07:45:11.177
24447,2024-11-30,11,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1805574.36,2024-11-30 05:11:01,2025-03-05 07:45:11.177
26445,2023-04-30,4,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1574570.27,2023-04-30 05:11:01,2025-03-05 07:45:11.130
26681,2023-07-31,7,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1755377.36,2023-07-31 05:11:01,2025-03-05 07:45:11.143
27182,2023-09-30,9,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1848464.37,2023-09-30 05:11:01,2025-03-05 07:45:11.143
27490,2022-10-31,10,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1460950.20,2022-10-31 05:11:01,2025-03-05 07:45:11.130
30781,2022-12-31,12,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1678172.66,2022-12-31 05:11:01,2025-03-05 07:45:11.130
32707,2024-05-31,5,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1768318.23,2024-05-31 05:11:01,2025-03-05 07:45:11.177
34449,2022-01-31,1,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1746950.61,2022-01-31 05:11:01,2025-03-05 07:45:11.020
34532,2024-09-30,9,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1895183.00,2024-09-30 05:11:01,2025-03-05 07:45:11.190
34921,2025-01-31,1,2025,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1663335.90,2025-01-31 05:11:01,2025-03-05 07:45:11.190
36510,2023-06-30,6,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1848033.88,2023-06-30 05:11:01,2025-03-05 07:45:11.143
37457,2024-10-31,10,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1948631.85,2024-10-31 05:11:01,2025-03-05 07:45:11.177
38484,2023-11-30,11,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1915735.87,2023-11-30 05:11:01,2025-03-05 07:45:11.160
40129,2022-09-30,9,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1647720.90,2022-09-30 05:11:01,2025-03-05 07:45:11.097
43648,2022-11-30,11,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1569057.98,2022-11-30 05:11:01,2025-03-05 07:45:11.130
46749,2024-07-31,7,2024,Total Domestic Sales,Total Domestic Sales of Coal,Ton,None,None,Actual,1763647.20,2024-07-31 05:11:01,2025-03-05 07:45:11.177
47255,2024-08-31,8,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1754440.46,2024-08-31 05:11:01,2025-03-05 07:45:11.177
48802,2022-02-28,2,2022,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1465499.84,2022-02-28 05:11:01,2025-03-05 07:45:11.037
48979,2024-12-31,12,2024,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1898486.78,2024-12-31 05:11:01,2025-03-05 07:45:11.190
49186,2023-12-31,12,2023,Total Domestic Sales,Total Domestic Sales of Coal,None,None,None,Actual,1747544.56,2023-12-31 05:11:01,2025-03-05 07:45:11.160

In [18]:
df_Sales_Domestic = df_Sales_Domestic.sort_values(by='Date')

df_Sales_Domestic = df_Sales_Domestic.groupby(['Date'])['amount'].sum().reset_index()
df_Sales_Domestic

          Date      amount
0   2022-01-31  1746950.61
1   2022-02-28  1465499.84
2   2022-03-31  1468489.08
3   2022-04-30  1701725.78
4   2022-05-31  1629473.03
5   2022-06-30  1449262.88
6   2022-07-31  1670935.10
7   2022-08-31  1684074.34
8   2022-09-30  1647720.90
9   2022-10-31  1460950.20
10  2022-11-30  1569057.98
11  2022-12-31  1678172.66
12  2023-01-31  1748073.90
13  2023-02-28  1753328.56
14  2023-03-31  1655423.69
15  2023-04-30  1574570.27
16  2023-05-31  1749562.67
17  2023-06-30  1848033.88
18  2023-07-31  1755377.36
19  2023-08-31  1822898.67
20  2023-09-30  1848464.37
21  2023-10-31  1984942.99
22  2023-11-30  1915735.87
23  2023-12-31  1747544.56
24  2024-01-31  2275939.28
25  2024-02-29  1678156.59
26  2024-03-31  1902777.33
27  2024-04-30  2077174.33
28  2024-05-31  1768318.23
29  2024-06-30  1867122.60
30  2024-07-31  1763647.20
31  2024-08-31  1754440.46
32  2024-09-30  1895183.00
33  2024-10-31  1948631.85
34  2024-11-30  1805574.36
35  2024-12-31  1898486.78
36  2025-01-31  1663335.90

In [19]:
df_Sales_Domestic.columns = ['ds','y']
df_Sales_Domestic['ds'] = pd.to_datetime(df_Sales_Domestic['ds'])

# Kombinasi parameter untuk tuning
changepoint_prior_scales = [ 0.1, 0.5, 1]
seasonality_modes = ['additive']
seasonality_prior_scales = [0.01, 0.1]

# Membuat list kombinasi parameter
param_combinations = list(itertools.product(changepoint_prior_scales, seasonality_modes, seasonality_prior_scales))

# Fungsi untuk menghitung SMAPE
def smape(actual, predicted):
    return 100 * np.mean(2 * np.abs(predicted - actual) / (np.abs(predicted) + np.abs(actual)))

# Menyimpan hasil tuning
best_smape = float('inf')
best_params = None

# Train dan test split
train_size = int(0.8 * len(df_Sales_Domestic))
train_data = df_Sales_Domestic[:train_size]
test_data = df_Sales_Domestic[train_size:]

# Looping untuk setiap kombinasi parameter
for changepoint_prior_scale, seasonality_mode, seasonality_prior_scale in param_combinations:
    
    # Inisialisasi model Prophet dengan parameter tuning
    model = Prophet(
        yearly_seasonality=True, 
        weekly_seasonality=True, 
        daily_seasonality=False,
        changepoint_prior_scale=changepoint_prior_scale,
        seasonality_mode=seasonality_mode,
        seasonality_prior_scale=seasonality_prior_scale,
        growth='linear'
    )
    model.add_seasonality(name='monthly', period=30, fourier_order=3)
    
    # Melatih model dengan data train
    model.fit(train_data)

    # Membuat dataframe masa depan yang mencakup periode data test
    future = model.make_future_dataframe(periods=len(test_data), freq='MS')

    # Melakukan prediksi
    forecast = model.predict(future)

    # Mengambil prediksi yang sesuai dengan data test
    forecast_test = forecast[-len(test_data):]

    # Menggabungkan data asli dengan prediksi
    test_data.loc[:, 'yhat'] = forecast_test['yhat'].values

    # Menghitung SMAPE untuk data test
    smape_value = smape(test_data['y'], test_data['yhat'])
    print(f"SMAPE dengan changepoint_prior_scale={changepoint_prior_scale}, seasonality_mode={seasonality_mode}, seasonality_prior_scale={seasonality_prior_scale}: {smape_value:.2f}%")

    # Menyimpan kombinasi parameter terbaik
    if smape_value < best_smape:
        best_smape = smape_value
        best_params = (changepoint_prior_scale, seasonality_mode, seasonality_prior_scale)

print(f"\nParameter terbaik: changepoint_prior_scale={best_params[0]}, seasonality_mode={best_params[1]}, seasonality_prior_scale={best_params[2]}")
print(f"SMAPE terbaik: {best_smape:.2f}%")

# Latih model dengan seluruh data menggunakan parameter terbaik
final_model = Prophet(
    yearly_seasonality=True, 
    weekly_seasonality=True, 
    daily_seasonality=False,
    changepoint_prior_scale=best_params[0],
    seasonality_mode=best_params[1],
    seasonality_prior_scale=best_params[2],
    growth='linear'
)
final_model.add_seasonality(name='monthly', period=30, fourier_order=3)

# Melatih model dengan seluruh data
final_model.fit(df_Sales_Domestic)

# Membuat dataframe masa depan untuk 6 bulan ke depan
future = final_model.make_future_dataframe(periods=12, freq='MS')

# Melakukan prediksi
forecast_final = final_model.predict(future)

# Menampilkan hasil prediksi
# print(forecast_final[['ds', 'yhat', 'yhat_lower', 'yhat_upper']])

# Menyimpan hasil prediksi ke dalam DataFrame
forecast_df_sales_df_Sales_Domestic = forecast_final[['ds', 'yhat']]

07:52:17 - cmdstanpy - INFO - Chain [1] start processing
07:52:17 - cmdstanpy - INFO - Chain [1] done processing
07:52:18 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.01: 7.76%

07:52:18 - cmdstanpy - INFO - Chain [1] done processing
07:52:18 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.1: 11.16%

07:52:19 - cmdstanpy - INFO - Chain [1] done processing
07:52:19 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.01: 3.87%

07:52:38 - cmdstanpy - INFO - Chain [1] done processing
07:52:38 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.1: 112.59%

07:52:39 - cmdstanpy - INFO - Chain [1] done processing
07:52:39 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=1, seasonality_mode=additive, seasonality_prior_scale=0.01: 4.24%

07:52:58 - cmdstanpy - INFO - Chain [1] done processing
07:52:58 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=1, seasonality_mode=additive, seasonality_prior_scale=0.1: 90.97%

Parameter terbaik: changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.01
SMAPE terbaik: 3.87%

07:52:59 - cmdstanpy - INFO - Chain [1] done processing

In [20]:

# Menambahkan data untuk 'Forecast'
forecast_rows_SE = pd.DataFrame({
    'Date': forecast_df_sales_df_Sales_Domestic['ds'],
    'Tonase': forecast_df_sales_df_Sales_Domestic['yhat'],
    'Jenis': 'Forecast',
    'Breakdown' : 'Total Sales Domestik'
})

df_actual_sales_forecast_df_sales_df_Sales_Domestic = pd.DataFrame({
    'Date': df_Sales_Domestic['ds'],
    'Tonase': df_Sales_Domestic['y'],
    'Jenis': 'Actual',
    'Breakdown' : 'Total Sales Domestik'
})


# Menggabungkan semua DataFrame
result_df_SD = pd.concat([df_actual_sales_forecast_df_sales_df_Sales_Domestic,forecast_rows_SE], ignore_index=True)
result_df_SD

         Date        Tonase     Jenis             Breakdown
0  2022-01-31  1.746951e+06    Actual  Total Sales Domestik
1  2022-02-28  1.465500e+06    Actual  Total Sales Domestik
2  2022-03-31  1.468489e+06    Actual  Total Sales Domestik
3  2022-04-30  1.701726e+06    Actual  Total Sales Domestik
4  2022-05-31  1.629473e+06    Actual  Total Sales Domestik
..        ...           ...       ...                   ...
81 2025-09-01  1.613172e+06  Forecast  Total Sales Domestik
82 2025-10-01  1.671364e+06  Forecast  Total Sales Domestik
83 2025-11-01  1.627764e+06  Forecast  Total Sales Domestik
84 2025-12-01  1.563317e+06  Forecast  Total Sales Domestik
85 2026-01-01  1.530874e+06  Forecast  Total Sales Domestik

[86 rows x 4 columns]

----

In [21]:
df_ASP = df[df['BreakDown']=='Average Market Price IDR']
df_ASP =df_ASP[df_ASP['tipe']=='Actual']

In [22]:
df_ASP

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
1454,2023-01-31,1,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1230003.11,2023-01-31 05:11:01,2025-03-05 07:45:11.050
1541,2024-04-30,4,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,952847.66,2024-04-30 05:11:01,2025-03-05 07:45:11.177
2165,2024-02-29,2,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,967697.62,2024-02-29 05:11:01,2025-03-05 07:45:11.160
5571,2022-01-31,1,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,930067.30,2022-01-31 05:11:01,2025-03-05 07:45:11.020
5875,2022-03-31,3,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1412002.98,2022-03-31 05:11:01,2025-03-05 07:45:11.083
6323,2023-03-31,3,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1094070.92,2023-03-31 05:11:01,2025-03-05 07:45:11.130
9128,2024-01-31,1,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,943557.59,2024-01-31 05:11:01,2025-03-05 07:45:11.160
9413,2023-04-30,4,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1074880.03,2023-04-30 05:11:01,2025-03-05 07:45:11.130
10385,2022-04-30,4,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1406561.92,2022-04-30 05:11:01,2025-03-05 07:45:11.083
10679,2022-05-31,5,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1279439.86,2022-05-31 05:11:01,2025-03-05 07:45:11.083
11048,2023-02-28,2,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1010886.24,2023-02-28 05:11:01,2025-03-05 07:45:11.067
15404,2022-06-30,6,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1260877.38,2022-06-30 05:11:01,2025-03-05 07:45:11.083
15465,2022-08-31,8,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1473301.70,2022-08-31 05:11:01,2025-03-05 07:45:11.097
17367,2023-05-31,5,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,961536.78,2023-05-31 05:11:01,2025-03-05 07:45:11.130
17710,2023-10-31,10,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,990051.57,2023-10-31 05:11:01,2025-03-05 07:45:11.143
19607,2023-07-31,7,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,881872.37,2023-07-31 05:11:01,2025-03-05 07:45:11.143
21196,2024-03-31,3,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,980823.25,2024-03-31 05:11:01,2025-03-05 07:45:11.177
21751,2022-07-31,7,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1436669.88,2022-07-31 05:11:01,2025-03-05 07:45:11.097
22835,2024-06-30,6,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,974000.80,2024-06-30 05:11:01,2025-03-05 07:45:11.177
22888,2024-11-30,11,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,985822.01,2024-11-30 05:11:01,2025-03-05 07:45:11.177
27572,2022-10-31,10,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1619053.21,2022-10-31 05:11:01,2025-03-05 07:45:11.113
29905,2023-08-31,8,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,911521.25,2023-08-31 05:11:01,2025-03-05 07:45:11.143
30694,2024-05-31,5,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,982573.86,2024-05-31 05:11:01,2025-03-05 07:45:11.177
33139,2023-09-30,9,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,946189.63,2023-09-30 05:11:01,2025-03-05 07:45:11.143
33632,2023-06-30,6,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,998931.49,2023-06-30 05:11:01,2025-03-05 07:45:11.143
35344,2024-09-30,9,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,931274.14,2024-09-30 05:11:01,2025-03-05 07:45:11.190
39477,2025-01-31,1,2025,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,950167.60,2025-01-31 05:11:01,2025-03-05 07:45:11.190
40024,2024-10-31,10,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,967134.80,2024-10-31 05:11:01,2025-03-05 07:45:11.177
40880,2022-12-31,12,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1224510.12,2022-12-31 05:11:01,2025-03-05 07:45:11.130
41529,2023-11-30,11,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,991886.11,2023-11-30 05:11:01,2025-03-05 07:45:11.160
42323,2024-12-31,12,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1104668.58,2024-12-31 05:11:01,2025-03-05 07:45:11.190
43987,2022-11-30,11,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1336206.34,2022-11-30 05:11:01,2025-03-05 07:45:11.130
44705,2022-09-30,9,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1323887.35,2022-09-30 05:11:01,2025-03-05 07:45:11.097
45120,2023-12-31,12,2023,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1212901.72,2023-12-31 05:11:01,2025-03-05 07:45:11.160
45542,2022-02-28,2,2022,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,1046655.14,2022-02-28 05:11:01,2025-03-05 07:45:11.037
47828,2024-08-31,8,2024,External Data,Average Market Price IDR,IDR/Ton,None,None,Actual,979162.94,2024-08-31 05:11:01,2025-03-05 07:45:11.177
48061,2024-07-31,7,2024,External Data,Average Market Price IDR,USD/Ton,None,ICI-3,Actual,990896.03,2024-07-31 05:11:01,2025-03-05 07:45:11.177

In [23]:
df_ASP = df_ASP.sort_values(by='Date')

df_ASP = df_ASP.groupby(['Date'])['amount'].sum().reset_index()
df_ASP

          Date      amount
0   2022-01-31   930067.30
1   2022-02-28  1046655.14
2   2022-03-31  1412002.98
3   2022-04-30  1406561.92
4   2022-05-31  1279439.86
5   2022-06-30  1260877.38
6   2022-07-31  1436669.88
7   2022-08-31  1473301.70
8   2022-09-30  1323887.35
9   2022-10-31  1619053.21
10  2022-11-30  1336206.34
11  2022-12-31  1224510.12
12  2023-01-31  1230003.11
13  2023-02-28  1010886.24
14  2023-03-31  1094070.92
15  2023-04-30  1074880.03
16  2023-05-31   961536.78
17  2023-06-30   998931.49
18  2023-07-31   881872.37
19  2023-08-31   911521.25
20  2023-09-30   946189.63
21  2023-10-31   990051.57
22  2023-11-30   991886.11
23  2023-12-31  1212901.72
24  2024-01-31   943557.59
25  2024-02-29   967697.62
26  2024-03-31   980823.25
27  2024-04-30   952847.66
28  2024-05-31   982573.86
29  2024-06-30   974000.80
30  2024-07-31   990896.03
31  2024-08-31   979162.94
32  2024-09-30   931274.14
33  2024-10-31   967134.80
34  2024-11-30   985822.01
35  2024-12-31  1104668.58
36  2025-01-31   950167.60

In [24]:
df_ASP.columns = ['ds','y']
df_ASP['ds'] = pd.to_datetime(df_ASP['ds'])

# Kombinasi parameter untuk tuning
changepoint_prior_scales = [ 0.1, 0.5, 1]
seasonality_modes = ['additive']
seasonality_prior_scales = [0.01, 0.1]

# Membuat list kombinasi parameter
param_combinations = list(itertools.product(changepoint_prior_scales, seasonality_modes, seasonality_prior_scales))

# Fungsi untuk menghitung SMAPE
def smape(actual, predicted):
    return 100 * np.mean(2 * np.abs(predicted - actual) / (np.abs(predicted) + np.abs(actual)))

# Menyimpan hasil tuning
best_smape = float('inf')
best_params = None

# Train dan test split
train_size = int(0.8 * len(df_ASP))
train_data = df_ASP[:train_size]
test_data = df_ASP[train_size:]

# Looping untuk setiap kombinasi parameter
for changepoint_prior_scale, seasonality_mode, seasonality_prior_scale in param_combinations:
    
    # Inisialisasi model Prophet dengan parameter tuning
    model = Prophet(
        yearly_seasonality=True, 
        weekly_seasonality=True, 
        daily_seasonality=False,
        changepoint_prior_scale=changepoint_prior_scale,
        seasonality_mode=seasonality_mode,
        seasonality_prior_scale=seasonality_prior_scale,
        growth='linear'
    )
    model.add_seasonality(name='monthly', period=30, fourier_order=3)
    
    # Melatih model dengan data train
    model.fit(train_data)

    # Membuat dataframe masa depan yang mencakup periode data test
    future = model.make_future_dataframe(periods=len(test_data), freq='MS')

    # Melakukan prediksi
    forecast = model.predict(future)

    # Mengambil prediksi yang sesuai dengan data test
    forecast_test = forecast[-len(test_data):]

    # Menggabungkan data asli dengan prediksi
    test_data.loc[:, 'yhat'] = forecast_test['yhat'].values

    # Menghitung SMAPE untuk data test
    smape_value = smape(test_data['y'], test_data['yhat'])
    print(f"SMAPE dengan changepoint_prior_scale={changepoint_prior_scale}, seasonality_mode={seasonality_mode}, seasonality_prior_scale={seasonality_prior_scale}: {smape_value:.2f}%")

    # Menyimpan kombinasi parameter terbaik
    if smape_value < best_smape:
        best_smape = smape_value
        best_params = (changepoint_prior_scale, seasonality_mode, seasonality_prior_scale)

print(f"\nParameter terbaik: changepoint_prior_scale={best_params[0]}, seasonality_mode={best_params[1]}, seasonality_prior_scale={best_params[2]}")
print(f"SMAPE terbaik: {best_smape:.2f}%")

# Latih model dengan seluruh data menggunakan parameter terbaik
final_model = Prophet(
    yearly_seasonality=True, 
    weekly_seasonality=True, 
    daily_seasonality=False,
    changepoint_prior_scale=best_params[0],
    seasonality_mode=best_params[1],
    seasonality_prior_scale=best_params[2],
    growth='linear'
)
final_model.add_seasonality(name='monthly', period=30, fourier_order=3)

# Melatih model dengan seluruh data
final_model.fit(df_ASP)

# Membuat dataframe masa depan untuk 6 bulan ke depan
future = final_model.make_future_dataframe(periods=12, freq='MS')

# Melakukan prediksi
forecast_final = final_model.predict(future)

# Menampilkan hasil prediksi
# print(forecast_final[['ds', 'yhat', 'yhat_lower', 'yhat_upper']])

# Menyimpan hasil prediksi ke dalam DataFrame
forecast_df_ASP = forecast_final[['ds', 'yhat']]

07:53:24 - cmdstanpy - INFO - Chain [1] start processing
07:53:24 - cmdstanpy - INFO - Chain [1] done processing
07:53:24 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.01: 10.08%

07:53:25 - cmdstanpy - INFO - Chain [1] done processing
07:53:25 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.1: 14.58%

07:53:25 - cmdstanpy - INFO - Chain [1] done processing
07:53:26 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.01: 5.56%

07:53:46 - cmdstanpy - INFO - Chain [1] done processing
07:53:46 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.1: 63.53%

07:53:46 - cmdstanpy - INFO - Chain [1] done processing
07:53:47 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=1, seasonality_mode=additive, seasonality_prior_scale=0.01: 5.90%

07:54:06 - cmdstanpy - INFO - Chain [1] done processing
07:54:06 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=1, seasonality_mode=additive, seasonality_prior_scale=0.1: 48.65%

Parameter terbaik: changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.01
SMAPE terbaik: 5.56%

07:54:06 - cmdstanpy - INFO - Chain [1] done processing

In [25]:

# Menambahkan data untuk 'Forecast'
forecast_rows_SE = pd.DataFrame({
    'Date': forecast_df_ASP['ds'],
    'Tonase': forecast_df_ASP['yhat'],
    'Jenis': 'Forecast',
    'Breakdown' : 'Avg. Selling Price'
})

df_actual_sales_forecast_df_ASP = pd.DataFrame({
    'Date': df_ASP['ds'],
    'Tonase': df_ASP['y'],
    'Jenis': 'Actual',
    'Breakdown' : 'Avg. Selling Price'
})



# Menggabungkan semua DataFrame
result_df_Avg_SP = pd.concat([df_actual_sales_forecast_df_ASP,forecast_rows_SE ], ignore_index=True)
result_df_Avg_SP

         Date        Tonase     Jenis           Breakdown
0  2022-01-31  9.300673e+05    Actual  Avg. Selling Price
1  2022-02-28  1.046655e+06    Actual  Avg. Selling Price
2  2022-03-31  1.412003e+06    Actual  Avg. Selling Price
3  2022-04-30  1.406562e+06    Actual  Avg. Selling Price
4  2022-05-31  1.279440e+06    Actual  Avg. Selling Price
..        ...           ...       ...                 ...
81 2025-09-01  1.014249e+06  Forecast  Avg. Selling Price
82 2025-10-01  9.811703e+05  Forecast  Avg. Selling Price
83 2025-11-01  1.061187e+06  Forecast  Avg. Selling Price
84 2025-12-01  1.013906e+06  Forecast  Avg. Selling Price
85 2026-01-01  1.081328e+06  Forecast  Avg. Selling Price

[86 rows x 4 columns]

---

In [26]:
df_ASP_Domestic = df[df['BreakDown']=='Average Domestic Price']
df_ASP_Domestic = df_ASP_Domestic[df_ASP_Domestic['tipe']=='Actual']
df_ASP_Domestic

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
553,2024-04-30,4,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,786049.90,2024-04-30 05:11:01,2025-03-05 07:45:11.177
761,2023-01-31,1,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,784671.54,2023-01-31 05:11:01,2025-03-05 07:45:11.050
4540,2022-05-31,5,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,784225.32,2022-05-31 05:11:01,2025-03-05 07:45:11.083
6211,2023-02-28,2,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,783259.54,2023-02-28 05:11:01,2025-03-05 07:45:11.067
6382,2024-01-31,1,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,802335.09,2024-01-31 05:11:01,2025-03-05 07:45:11.160
6461,2022-01-31,1,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,777962.82,2022-01-31 05:11:01,2025-03-05 07:45:11.020
6594,2023-03-31,3,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,764892.56,2023-03-31 05:11:01,2025-03-05 07:45:11.130
7867,2023-10-31,10,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,750665.39,2023-10-31 05:11:01,2025-03-05 07:45:11.143
8412,2024-02-29,2,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,761575.51,2024-02-29 05:11:01,2025-03-05 07:45:11.160
8779,2022-04-30,4,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,918322.94,2022-04-30 05:11:01,2025-03-05 07:45:11.083
12052,2022-03-31,3,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,782620.39,2022-03-31 05:11:01,2025-03-05 07:45:11.083
12277,2023-05-31,5,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,786885.54,2023-05-31 05:11:01,2025-03-05 07:45:11.130
13367,2022-07-31,7,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,1010116.57,2022-07-31 05:11:01,2025-03-05 07:45:11.097
15339,2022-06-30,6,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,798864.42,2022-06-30 05:11:01,2025-03-05 07:45:11.083
18636,2023-04-30,4,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,790785.59,2023-04-30 05:11:01,2025-03-05 07:45:11.130
20560,2024-03-31,3,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,781168.13,2024-03-31 05:11:01,2025-03-05 07:45:11.177
21090,2024-05-31,5,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,767472.22,2024-05-31 05:11:01,2025-03-05 07:45:11.177
22750,2024-11-30,11,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,795617.55,2024-11-30 05:11:01,2025-03-05 07:45:11.177
23400,2024-06-30,6,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,777137.61,2024-06-30 05:11:01,2025-03-05 07:45:11.177
24595,2023-06-30,6,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,784368.44,2023-06-30 05:11:01,2025-03-05 07:45:11.143
26119,2024-09-30,9,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,762852.94,2024-09-30 05:11:01,2025-03-05 07:45:11.190
26511,2022-08-31,8,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,790729.89,2022-08-31 05:11:01,2025-03-05 07:45:11.097
27866,2022-10-31,10,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,785098.65,2022-10-31 05:11:01,2025-03-05 07:45:11.130
28561,2023-07-31,7,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,739776.94,2023-07-31 05:11:01,2025-03-05 07:45:11.143
29874,2023-08-31,8,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,756061.88,2023-08-31 05:11:01,2025-03-05 07:45:11.143
33228,2023-11-30,11,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,751213.20,2023-11-30 05:11:01,2025-03-05 07:45:11.160
33743,2023-09-30,9,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,736588.50,2023-09-30 05:11:01,2025-03-05 07:45:11.143
34797,2022-12-31,12,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,908970.34,2022-12-31 05:11:01,2025-03-05 07:45:11.130
36781,2024-10-31,10,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,793047.58,2024-10-31 05:11:01,2025-03-05 07:45:11.177
40802,2022-09-30,9,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,787640.80,2022-09-30 05:11:01,2025-03-05 07:45:11.097
42317,2024-12-31,12,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,1017623.55,2024-12-31 05:11:01,2025-03-05 07:45:11.190
42685,2023-12-31,12,2023,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,1128536.46,2023-12-31 05:11:01,2025-03-05 07:45:11.160
44766,2022-11-30,11,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,822040.76,2022-11-30 05:11:01,2025-03-05 07:45:11.130
44949,2025-01-31,1,2025,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,769437.29,2025-01-31 05:11:01,2025-03-05 07:45:11.190
45744,2022-02-28,2,2022,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,754704.81,2022-02-28 05:11:01,2025-03-05 07:45:11.037
45826,2024-07-31,7,2024,External Data,Average Domestic Price,None,Japan,None,Actual,761279.89,2024-07-31 05:11:01,2025-03-05 07:45:11.177
47475,2024-08-31,8,2024,External Data,Average Domestic Price,IDR/Ton,None,None,Actual,768877.81,2024-08-31 05:11:01,2025-03-05 07:45:11.177

In [27]:
df_ASP_Domestic = df_ASP_Domestic.sort_values(by='Date')

df_ASP_Domestic = df_ASP_Domestic.groupby(['Date'])['amount'].sum().reset_index()
df_ASP_Domestic

          Date      amount
0   2022-01-31   777962.82
1   2022-02-28   754704.81
2   2022-03-31   782620.39
3   2022-04-30   918322.94
4   2022-05-31   784225.32
5   2022-06-30   798864.42
6   2022-07-31  1010116.57
7   2022-08-31   790729.89
8   2022-09-30   787640.80
9   2022-10-31   785098.65
10  2022-11-30   822040.76
11  2022-12-31   908970.34
12  2023-01-31   784671.54
13  2023-02-28   783259.54
14  2023-03-31   764892.56
15  2023-04-30   790785.59
16  2023-05-31   786885.54
17  2023-06-30   784368.44
18  2023-07-31   739776.94
19  2023-08-31   756061.88
20  2023-09-30   736588.50
21  2023-10-31   750665.39
22  2023-11-30   751213.20
23  2023-12-31  1128536.46
24  2024-01-31   802335.09
25  2024-02-29   761575.51
26  2024-03-31   781168.13
27  2024-04-30   786049.90
28  2024-05-31   767472.22
29  2024-06-30   777137.61
30  2024-07-31   761279.89
31  2024-08-31   768877.81
32  2024-09-30   762852.94
33  2024-10-31   793047.58
34  2024-11-30   795617.55
35  2024-12-31  1017623.55
36  2025-01-31   769437.29

In [28]:
df_ASP_Domestic.columns = ['ds','y']
df_ASP_Domestic['ds'] = pd.to_datetime(df_ASP_Domestic['ds'])

# Kombinasi parameter untuk tuning
changepoint_prior_scales = [0.01, 0.02]
seasonality_modes = ['additive']
seasonality_prior_scales = [0.01, 0.05, 0.1]

# Membuat list kombinasi parameter
param_combinations = list(itertools.product(changepoint_prior_scales, seasonality_modes, seasonality_prior_scales))

# Fungsi untuk menghitung SMAPE
def smape(actual, predicted):
    return 100 * np.mean(2 * np.abs(predicted - actual) / (np.abs(predicted) + np.abs(actual)))

# Menyimpan hasil tuning
best_smape = float('inf')
best_params = None

# Train dan test split
train_size = int(0.8 * len(df_ASP_Domestic))
train_data = df_ASP_Domestic[:train_size]
test_data = df_ASP_Domestic[train_size:]

# Looping untuk setiap kombinasi parameter
for changepoint_prior_scale, seasonality_mode, seasonality_prior_scale in param_combinations:
    
    # Inisialisasi model Prophet dengan parameter tuning
    model = Prophet(
        yearly_seasonality=True, 
        weekly_seasonality=True, 
        daily_seasonality=False,
        changepoint_prior_scale=changepoint_prior_scale,
        seasonality_mode=seasonality_mode,
        seasonality_prior_scale=seasonality_prior_scale,
        growth='linear'
    )
    model.add_seasonality(name='monthly', period=30, fourier_order=3)
    
    # Melatih model dengan data train
    model.fit(train_data)

    # Membuat dataframe masa depan yang mencakup periode data test
    future = model.make_future_dataframe(periods=len(test_data), freq='MS')

    # Melakukan prediksi
    forecast = model.predict(future)

    # Mengambil prediksi yang sesuai dengan data test
    forecast_test = forecast[-len(test_data):]

    # Menggabungkan data asli dengan prediksi
    test_data.loc[:, 'yhat'] = forecast_test['yhat'].values

    # Menghitung SMAPE untuk data test
    smape_value = smape(test_data['y'], test_data['yhat'])
    print(f"SMAPE dengan changepoint_prior_scale={changepoint_prior_scale}, seasonality_mode={seasonality_mode}, seasonality_prior_scale={seasonality_prior_scale}: {smape_value:.2f}%")

    # Menyimpan kombinasi parameter terbaik
    if smape_value < best_smape:
        best_smape = smape_value
        best_params = (changepoint_prior_scale, seasonality_mode, seasonality_prior_scale)

print(f"\nParameter terbaik: changepoint_prior_scale={best_params[0]}, seasonality_mode={best_params[1]}, seasonality_prior_scale={best_params[2]}")
print(f"SMAPE terbaik: {best_smape:.2f}%")

# Latih model dengan seluruh data menggunakan parameter terbaik
final_model = Prophet(
    yearly_seasonality=True, 
    weekly_seasonality=True, 
    daily_seasonality=False,
    changepoint_prior_scale=best_params[0],
    seasonality_mode=best_params[1],
    seasonality_prior_scale=best_params[2],
    growth='linear'
)
final_model.add_seasonality(name='monthly', period=30, fourier_order=3)

# Melatih model dengan seluruh data
final_model.fit(df_ASP_Domestic)

# Membuat dataframe masa depan untuk 6 bulan ke depan
future = final_model.make_future_dataframe(periods=12, freq='MS')

# Melakukan prediksi
forecast_final = final_model.predict(future)

# Menampilkan hasil prediksi
# print(forecast_final[['ds', 'yhat', 'yhat_lower', 'yhat_upper']])

# Menyimpan hasil prediksi ke dalam DataFrame
forecast_ASP_Domestic = forecast_final[['ds', 'yhat']]

07:54:21 - cmdstanpy - INFO - Chain [1] start processing
07:54:21 - cmdstanpy - INFO - Chain [1] done processing
07:54:21 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.01: 7.97%

07:54:21 - cmdstanpy - INFO - Chain [1] done processing
07:54:21 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.05: 13.51%

07:54:21 - cmdstanpy - INFO - Chain [1] done processing
07:54:22 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.1: 13.47%

07:54:22 - cmdstanpy - INFO - Chain [1] done processing
07:54:22 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.02, seasonality_mode=additive, seasonality_prior_scale=0.01: 7.99%

07:54:22 - cmdstanpy - INFO - Chain [1] done processing
07:54:22 - cmdstanpy - INFO - Chain [1] start processing
07:54:23 - cmdstanpy - INFO - Chain [1] done processing

SMAPE dengan changepoint_prior_scale=0.02, seasonality_mode=additive, seasonality_prior_scale=0.05: 13.26%

07:54:23 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.02, seasonality_mode=additive, seasonality_prior_scale=0.1: 13.57%

Parameter terbaik: changepoint_prior_scale=0.01, seasonality_mode=additive, seasonality_prior_scale=0.01
SMAPE terbaik: 7.97%

07:54:23 - cmdstanpy - INFO - Chain [1] done processing

In [29]:

# Menambahkan data untuk 'Forecast'
forecast_rows_SE = pd.DataFrame({
    'Date': forecast_ASP_Domestic['ds'],
    'Tonase': forecast_ASP_Domestic['yhat'],
    'Jenis': 'Forecast',
    'Breakdown' : 'Avg. Selling Price Domestic'
})

df_actual_sales_forecast_df_ASP_Domestic = pd.DataFrame({
    'Date': df_ASP_Domestic['ds'],
    'Tonase': df_ASP_Domestic['y'],
    'Jenis': 'Actual',
    'Breakdown' : 'Avg. Selling Price Domestic'
})



# Menggabungkan semua DataFrame
result_df_Avg_SP_Dom = pd.concat([df_actual_sales_forecast_df_ASP_Domestic,forecast_rows_SE], ignore_index=True)
result_df_Avg_SP_Dom

         Date         Tonase     Jenis                    Breakdown
0  2022-01-31  777962.820000    Actual  Avg. Selling Price Domestic
1  2022-02-28  754704.810000    Actual  Avg. Selling Price Domestic
2  2022-03-31  782620.390000    Actual  Avg. Selling Price Domestic
3  2022-04-30  918322.940000    Actual  Avg. Selling Price Domestic
4  2022-05-31  784225.320000    Actual  Avg. Selling Price Domestic
..        ...            ...       ...                          ...
81 2025-09-01  761665.638112  Forecast  Avg. Selling Price Domestic
82 2025-10-01  771158.701222  Forecast  Avg. Selling Price Domestic
83 2025-11-01  778092.518885  Forecast  Avg. Selling Price Domestic
84 2025-12-01  756666.060513  Forecast  Avg. Selling Price Domestic
85 2026-01-01  915713.874852  Forecast  Avg. Selling Price Domestic

[86 rows x 4 columns]

---

In [30]:
df_ASP_Export = df[df['BreakDown']=='Average Export Price']
df_ASP_Export = df_ASP_Export[df_ASP_Export['tipe']=='Actual']
df_ASP_Export

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
421,2023-01-31,1,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1831040.36,2023-01-31 05:11:01,2025-03-05 07:45:11.050
2159,2024-02-29,2,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1216780.53,2024-02-29 05:11:01,2025-03-05 07:45:11.160
3795,2024-01-31,1,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1239080.65,2024-01-31 05:11:01,2025-03-05 07:45:11.160
5364,2022-05-31,5,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2066416.17,2022-05-31 05:11:01,2025-03-05 07:45:11.083
5962,2023-03-31,3,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1415245.73,2023-03-31 05:11:01,2025-03-05 07:45:11.130
6254,2023-02-28,2,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1623757.43,2023-02-28 05:11:01,2025-03-05 07:45:11.067
6697,2022-04-30,4,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2215393.21,2022-04-30 05:11:01,2025-03-05 07:45:11.083
6810,2022-03-31,3,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2096535.74,2022-03-31 05:11:01,2025-03-05 07:45:11.083
8064,2024-04-30,4,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1240801.70,2024-04-30 05:11:01,2025-03-05 07:45:11.177
12186,2024-03-31,3,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1269914.13,2024-03-31 05:11:01,2025-03-05 07:45:11.177
14378,2022-06-30,6,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2072909.63,2022-06-30 05:11:01,2025-03-05 07:45:11.083
14953,2023-05-31,5,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1362773.67,2023-05-31 05:11:01,2025-03-05 07:45:11.130
17220,2023-10-31,10,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1337046.00,2023-10-31 05:11:01,2025-03-05 07:45:11.143
18227,2022-08-31,8,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2372036.75,2022-08-31 05:11:01,2025-03-05 07:45:11.097
18916,2022-07-31,7,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2199046.36,2022-07-31 05:11:01,2025-03-05 07:45:11.097
19951,2023-07-31,7,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1044021.68,2023-07-31 05:11:01,2025-03-05 07:45:11.143
22882,2024-11-30,11,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1156874.95,2024-11-30 05:11:01,2025-03-05 07:45:11.177
25600,2023-04-30,4,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1389122.09,2023-04-30 05:11:01,2025-03-05 07:45:11.130
27092,2023-09-30,9,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1225825.47,2023-09-30 05:11:01,2025-03-05 07:45:11.143
27789,2022-10-31,10,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2431769.18,2022-10-31 05:11:01,2025-03-05 07:45:11.130
28958,2023-08-31,8,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1142755.56,2023-08-31 05:11:01,2025-03-05 07:45:11.143
30505,2024-06-30,6,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1200042.88,2024-06-30 05:11:01,2025-03-05 07:45:11.177
32281,2024-09-30,9,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1106390.71,2024-09-30 05:11:01,2025-03-05 07:45:11.190
32379,2024-05-31,5,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1186480.32,2024-05-31 05:11:01,2025-03-05 07:45:11.177
33626,2023-06-30,6,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1311581.45,2023-06-30 05:11:01,2025-03-05 07:45:11.143
34307,2022-12-31,12,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,1751599.42,2022-12-31 05:11:01,2025-03-05 07:45:11.130
34952,2022-01-31,1,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,1700916.45,2022-01-31 05:11:01,2025-03-05 07:45:11.020
36787,2024-10-31,10,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1137014.76,2024-10-31 05:11:01,2025-03-05 07:45:11.177
38606,2023-11-30,11,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1347042.43,2023-11-30 05:11:01,2025-03-05 07:45:11.160
38949,2022-09-30,9,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,1854725.70,2022-09-30 05:11:01,2025-03-05 07:45:11.097
38967,2025-01-31,1,2025,External Data,Average Export Price,IDR/Ton,None,None,Actual,1156008.52,2025-01-31 05:11:01,2025-03-05 07:45:11.190
42375,2022-11-30,11,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,2197910.23,2022-11-30 05:11:01,2025-03-05 07:45:11.130
43178,2024-12-31,12,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1189148.35,2024-12-31 05:11:01,2025-03-05 07:45:11.190
46457,2023-12-31,12,2023,External Data,Average Export Price,IDR/Ton,None,None,Actual,1301916.39,2023-12-31 05:11:01,2025-03-05 07:45:11.160
47499,2024-08-31,8,2024,External Data,Average Export Price,IDR/Ton,None,None,Actual,1166552.20,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49098,2022-02-28,2,2022,External Data,Average Export Price,IDR/Ton,None,None,Actual,1770779.41,2022-02-28 05:11:01,2025-03-05 07:45:11.037
49227,2024-07-31,7,2024,External Data,Average Export Price,None,Malaysia,None,Actual,1191562.53,2024-07-31 05:11:01,2025-03-05 07:45:11.177

In [31]:
df_ASP_Export = df_ASP_Export.sort_values(by='Date')

df_ASP_Export = df_ASP_Export.groupby(['Date'])['amount'].sum().reset_index()
df_ASP_Export

          Date      amount
0   2022-01-31  1700916.45
1   2022-02-28  1770779.41
2   2022-03-31  2096535.74
3   2022-04-30  2215393.21
4   2022-05-31  2066416.17
5   2022-06-30  2072909.63
6   2022-07-31  2199046.36
7   2022-08-31  2372036.75
8   2022-09-30  1854725.70
9   2022-10-31  2431769.18
10  2022-11-30  2197910.23
11  2022-12-31  1751599.42
12  2023-01-31  1831040.36
13  2023-02-28  1623757.43
14  2023-03-31  1415245.73
15  2023-04-30  1389122.09
16  2023-05-31  1362773.67
17  2023-06-30  1311581.45
18  2023-07-31  1044021.68
19  2023-08-31  1142755.56
20  2023-09-30  1225825.47
21  2023-10-31  1337046.00
22  2023-11-30  1347042.43
23  2023-12-31  1301916.39
24  2024-01-31  1239080.65
25  2024-02-29  1216780.53
26  2024-03-31  1269914.13
27  2024-04-30  1240801.70
28  2024-05-31  1186480.32
29  2024-06-30  1200042.88
30  2024-07-31  1191562.53
31  2024-08-31  1166552.20
32  2024-09-30  1106390.71
33  2024-10-31  1137014.76
34  2024-11-30  1156874.95
35  2024-12-31  1189148.35
36  2025-01-31  1156008.52

In [32]:
df_ASP_Export.columns = ['ds','y']
df_ASP_Export['ds'] = pd.to_datetime(df_ASP_Export['ds'])

# Kombinasi parameter untuk tuning
changepoint_prior_scales = [ 0.1, 0.5, 1]
seasonality_modes = ['additive']
seasonality_prior_scales = [0.01, 0.1]

# Membuat list kombinasi parameter
param_combinations = list(itertools.product(changepoint_prior_scales, seasonality_modes, seasonality_prior_scales))

# Fungsi untuk menghitung SMAPE
def smape(actual, predicted):
    return 100 * np.mean(2 * np.abs(predicted - actual) / (np.abs(predicted) + np.abs(actual)))

# Menyimpan hasil tuning
best_smape = float('inf')
best_params = None

# Train dan test split
train_size = int(0.8 * len(df_ASP_Export))
train_data = df_ASP_Export[:train_size]
test_data = df_ASP_Export[train_size:]

# Looping untuk setiap kombinasi parameter
for changepoint_prior_scale, seasonality_mode, seasonality_prior_scale in param_combinations:
    
    # Inisialisasi model Prophet dengan parameter tuning
    model = Prophet(
        yearly_seasonality=True, 
        weekly_seasonality=True, 
        daily_seasonality=False,
        changepoint_prior_scale=changepoint_prior_scale,
        seasonality_mode=seasonality_mode,
        seasonality_prior_scale=seasonality_prior_scale,
        growth='linear'
    )
    model.add_seasonality(name='monthly', period=30, fourier_order=3)
    
    # Melatih model dengan data train
    model.fit(train_data)

    # Membuat dataframe masa depan yang mencakup periode data test
    future = model.make_future_dataframe(periods=len(test_data), freq='MS')

    # Melakukan prediksi
    forecast = model.predict(future)

    # Mengambil prediksi yang sesuai dengan data test
    forecast_test = forecast[-len(test_data):]

    # Menggabungkan data asli dengan prediksi
    test_data.loc[:, 'yhat'] = forecast_test['yhat'].values

    # Menghitung SMAPE untuk data test
    smape_value = smape(test_data['y'], test_data['yhat'])
    print(f"SMAPE dengan changepoint_prior_scale={changepoint_prior_scale}, seasonality_mode={seasonality_mode}, seasonality_prior_scale={seasonality_prior_scale}: {smape_value:.2f}%")

    # Menyimpan kombinasi parameter terbaik
    if smape_value < best_smape:
        best_smape = smape_value
        best_params = (changepoint_prior_scale, seasonality_mode, seasonality_prior_scale)

print(f"\nParameter terbaik: changepoint_prior_scale={best_params[0]}, seasonality_mode={best_params[1]}, seasonality_prior_scale={best_params[2]}")
print(f"SMAPE terbaik: {best_smape:.2f}%")

# Latih model dengan seluruh data menggunakan parameter terbaik
final_model = Prophet(
    yearly_seasonality=True, 
    weekly_seasonality=True, 
    daily_seasonality=False,
    changepoint_prior_scale=best_params[0],
    seasonality_mode=best_params[1],
    seasonality_prior_scale=best_params[2],
    growth='linear'
)
final_model.add_seasonality(name='monthly', period=30, fourier_order=3)

# Melatih model dengan seluruh data
final_model.fit(df_ASP_Export)

# Membuat dataframe masa depan untuk 6 bulan ke depan
future = final_model.make_future_dataframe(periods=12, freq='MS')

# Melakukan prediksi
forecast_final = final_model.predict(future)

# Menampilkan hasil prediksi
# print(forecast_final[['ds', 'yhat', 'yhat_lower', 'yhat_upper']])

# Menyimpan hasil prediksi ke dalam DataFrame
forecast_ASP_Export = forecast_final[['ds', 'yhat']]

07:54:36 - cmdstanpy - INFO - Chain [1] start processing
07:54:36 - cmdstanpy - INFO - Chain [1] done processing
07:54:36 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.01: 20.32%

07:54:37 - cmdstanpy - INFO - Chain [1] done processing
07:54:37 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.1, seasonality_mode=additive, seasonality_prior_scale=0.1: 23.50%

07:54:38 - cmdstanpy - INFO - Chain [1] done processing
07:54:38 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.01: 8.61%

07:54:59 - cmdstanpy - INFO - Chain [1] done processing
07:54:59 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=0.5, seasonality_mode=additive, seasonality_prior_scale=0.1: 87.89%

07:55:00 - cmdstanpy - INFO - Chain [1] done processing
07:55:00 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=1, seasonality_mode=additive, seasonality_prior_scale=0.01: 5.92%

07:55:21 - cmdstanpy - INFO - Chain [1] done processing
07:55:21 - cmdstanpy - INFO - Chain [1] start processing

SMAPE dengan changepoint_prior_scale=1, seasonality_mode=additive, seasonality_prior_scale=0.1: 59.55%

Parameter terbaik: changepoint_prior_scale=1, seasonality_mode=additive, seasonality_prior_scale=0.01
SMAPE terbaik: 5.92%

07:55:22 - cmdstanpy - INFO - Chain [1] done processing

In [33]:
# Menambahkan data untuk 'Forecast'
forecast_rows_SE = pd.DataFrame({
    'Date':forecast_ASP_Export['ds'],
    'Tonase': forecast_ASP_Export['yhat'],
    'Jenis': 'Forecast',
    'Breakdown' : 'Avg. Selling Price Export'
})

df_actual_sales_forecast_df_ASP_Export = pd.DataFrame({
    'Date': df_ASP_Export['ds'],
    'Tonase': df_ASP_Export['y'],
    'Jenis': 'Actual',
    'Breakdown' : 'Avg. Selling Price Export'
})


# Menggabungkan semua DataFrame
result_df_Avg_SP_Exp = pd.concat([df_actual_sales_forecast_df_ASP_Export,forecast_rows_SE ], ignore_index=True)
result_df_Avg_SP_Exp

         Date        Tonase     Jenis                  Breakdown
0  2022-01-31  1.700916e+06    Actual  Avg. Selling Price Export
1  2022-02-28  1.770779e+06    Actual  Avg. Selling Price Export
2  2022-03-31  2.096536e+06    Actual  Avg. Selling Price Export
3  2022-04-30  2.215393e+06    Actual  Avg. Selling Price Export
4  2022-05-31  2.066416e+06    Actual  Avg. Selling Price Export
..        ...           ...       ...                        ...
81 2025-09-01  1.148036e+06  Forecast  Avg. Selling Price Export
82 2025-10-01  1.054503e+06  Forecast  Avg. Selling Price Export
83 2025-11-01  1.156312e+06  Forecast  Avg. Selling Price Export
84 2025-12-01  1.142294e+06  Forecast  Avg. Selling Price Export
85 2026-01-01  1.008743e+06  Forecast  Avg. Selling Price Export

[86 rows x 4 columns]

---

In [34]:
df_Final = pd.concat((result_df_Sales, result_df_SD, result_df_Sales_Export, result_df_Avg_SP, result_df_Avg_SP_Dom, result_df_Avg_SP_Exp), axis = 0)
df_Final

         Date        Tonase     Jenis                  Breakdown
0  2022-01-31  2.091660e+06    Actual                Total Sales
1  2022-02-28  2.056356e+06    Actual                Total Sales
2  2022-03-31  2.818668e+06    Actual                Total Sales
3  2022-04-30  2.728947e+06    Actual                Total Sales
4  2022-05-31  2.654839e+06    Actual                Total Sales
..        ...           ...       ...                        ...
81 2025-09-01  1.148036e+06  Forecast  Avg. Selling Price Export
82 2025-10-01  1.054503e+06  Forecast  Avg. Selling Price Export
83 2025-11-01  1.156312e+06  Forecast  Avg. Selling Price Export
84 2025-12-01  1.142294e+06  Forecast  Avg. Selling Price Export
85 2026-01-01  1.008743e+06  Forecast  Avg. Selling Price Export

[514 rows x 4 columns]

In [35]:
df_Final = df_Final.reset_index(drop=True)
print(df_Final)

          Date        Tonase     Jenis                  Breakdown
0   2022-01-31  2.091660e+06    Actual                Total Sales
1   2022-02-28  2.056356e+06    Actual                Total Sales
2   2022-03-31  2.818668e+06    Actual                Total Sales
3   2022-04-30  2.728947e+06    Actual                Total Sales
4   2022-05-31  2.654839e+06    Actual                Total Sales
..         ...           ...       ...                        ...
509 2025-09-01  1.148036e+06  Forecast  Avg. Selling Price Export
510 2025-10-01  1.054503e+06  Forecast  Avg. Selling Price Export
511 2025-11-01  1.156312e+06  Forecast  Avg. Selling Price Export
512 2025-12-01  1.142294e+06  Forecast  Avg. Selling Price Export
513 2026-01-01  1.008743e+06  Forecast  Avg. Selling Price Export

[514 rows x 4 columns]

---

In [63]:
# DF Plan
df_plan = df[df['tipe']=='RKAP'].copy()
df_plan

,Date,bulan,tahun,Indicator,BreakDown,Unit,Country,Source,tipe,amount,last_updated,Updated_Date
1,2023-01-31,1,2023,Operating Expenses,Fuel Usage of Marketing,IDR,None,None,RKAP,2.840146e+09,2023-01-31 05:11:01,2025-03-05 07:45:11.143
7,2023-01-31,1,2023,Operating Expenses,Other Selling Expenses of Marketing,IDR,None,None,RKAP,3.358052e+10,2023-01-31 05:11:01,2025-03-05 07:45:11.050
13,2023-01-31,1,2023,Cash Conversion Cycle,Cash Conversion Cycle,Days,None,None,RKAP,0.000000e+00,2023-01-31 05:11:01,2025-03-05 07:45:11.050
19,2023-01-31,1,2023,Cost of Goods Sold,"Salaries, Wages, and Employee Benefits",IDR,None,None,RKAP,7.293799e+10,2023-01-31 05:11:01,2025-03-05 07:45:11.050
25,2023-01-31,1,2023,Current Assets,Total Current Assets,IDR,None,None,RKAP,2.305630e+13,2023-01-31 05:11:01,2025-03-05 07:45:11.050
...,...,...,...,...,...,...,...,...,...,...,...,...
49383,2024-08-31,8,2024,Financing Activities Details,Payment from stockholders loan,IDR,None,None,RKAP,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49389,2024-08-31,8,2024,Financing Activities Details,Payment to stockholders loan,IDR,None,None,RKAP,0.000000e+00,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49395,2024-08-31,8,2024,Non Current Assets,Others of Non Current Assets,IDR,None,None,RKAP,8.036372e+12,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49401,2024-08-31,8,2024,Operating Expenses,Business Travel and Education,IDR,None,None,RKAP,1.189166e+10,2024-08-31 05:11:01,2025-03-05 07:45:11.177
49407,2024-08-31,8,2024,Operating Expenses,Depreciation and Amortization of Marketing,IDR,None,None,RKAP,1.844921e+10,2024-08-31 05:11:01,2025-03-05 07:45:11.177

In [64]:
df_plan_sales = df_plan[df_plan['BreakDown'].isin(['Total Domestic Sales of Coal','Total Export Sales of Coal'])].copy()
df_plan_sales = df_plan_sales.groupby(['Date'])['amount'].sum().reset_index()
df_plan_sales

          Date      amount
0   2022-01-31  2746000.00
1   2022-02-28  2791200.00
2   2022-03-31  2988900.00
3   2022-04-30  2932200.00
4   2022-05-31  3100500.00
5   2022-06-30  3018300.00
6   2022-07-31  3198600.00
7   2022-08-31  3231600.00
8   2022-09-30  3187800.00
9   2022-10-31  3323900.00
10  2022-11-30  3248400.00
11  2022-12-31  3332600.00
12  2023-01-31  3037700.00
13  2023-02-28  3079633.33
14  2023-03-31  3071400.00
15  2023-04-30  3501000.00
16  2023-05-31  3662000.00
17  2023-06-30  3574800.00
18  2023-07-31  3648600.00
19  2023-08-31  3652200.00
20  2023-09-30  3557500.00
21  2023-10-31  3652800.00
22  2023-11-30  3546900.00
23  2023-12-31  3518400.00
24  2024-01-31  3363899.16
25  2024-02-29  3443180.11
26  2024-03-31  3646027.45
27  2024-04-30  3565953.04
28  2024-05-31  3667877.34
29  2024-06-30  3572221.41
30  2024-07-31  2160800.00
31  2024-08-31  3678752.37
32  2024-09-30  3572953.04
33  2024-10-31  3677352.37
34  2024-11-30  3589553.04
35  2024-12-31  3654653.37
36  2025-01-31  4150375.00

In [66]:
df_plan_sales_domestik = df_plan[df_plan['BreakDown'] == 'Total Domestic Sales of Coal'].groupby(['Date'])['amount'].sum().reset_index()
df_plan_sales_export = df_plan[df_plan['BreakDown'] == 'Total Export Sales of Coal'].groupby(['Date'])['amount'].sum().reset_index()
df_plan_ASP_Export = df_plan[df_plan['BreakDown'] == 'Average Export Price'].groupby(['Date'])['amount'].sum().reset_index()
df_plan_ASP = df_plan[df_plan['BreakDown'] == 'Average Market Price IDR'].groupby(['Date'])['amount'].sum().reset_index()
df_plan_ASP_Domestic = df_plan[df_plan['BreakDown'] == 'Average Domestic Price'].groupby(['Date'])['amount'].sum().reset_index()

In [67]:
from datetime import datetime
# Menambahkan data untuk 'Forecast'
df_plan_sales = pd.DataFrame({
    'Date':df_plan_sales['Date'],
    'Tonase': df_plan_sales['amount'],
    'Jenis': 'Plan',
    'Breakdown' : 'Total Sales'
})

df_plan_sales_domestik = pd.DataFrame({
    'Date': df_plan_sales_domestik['Date'],
    'Tonase': df_plan_sales_domestik['amount'],
    'Jenis': 'Plan',
    'Breakdown' : 'Total Sales Domestik'
})
df_plan_sales_export = pd.DataFrame({
    'Date': df_plan_sales_export['Date'],
    'Tonase': df_plan_sales_export['amount'],
    'Jenis': 'Plan',
    'Breakdown' : 'Total Sales Ekspor'
})
df_plan_ASP = pd.DataFrame({
    'Date': df_plan_ASP['Date'],
    'Tonase': df_plan_ASP['amount'],
    'Jenis': 'Plan',
    'Breakdown' : 'Avg. Selling Price'
})
df_plan_ASP_Export = pd.DataFrame({
    'Date': df_plan_ASP_Export['Date'],
    'Tonase': df_plan_ASP_Export['amount'],
    'Jenis': 'Plan',
    'Breakdown' : 'Avg. Selling Price Export'
})
df_plan_ASP_Domestic = pd.DataFrame({
    'Date': df_plan_ASP_Domestic['Date'],
    'Tonase': df_plan_ASP_Domestic['amount'],
    'Jenis': 'Plan',
    'Breakdown' : 'Avg. Selling Price Domestic'
})
new_row = pd.DataFrame({
    'Date': [datetime.now()],  # Menggunakan datetime sekarang
    'Tonase': [0],  # Tonase diisi 0
    'Jenis': ['Actual'],  # Jenis diisi "Actual"
    'Breakdown': ['Last Update']  # Breakdown diisi "Last Update"
})

# Menggabungkan semua DataFrame
df_All = pd.concat([df_plan_sales, df_plan_sales_domestik, df_plan_sales_export, df_plan_ASP, df_plan_ASP_Domestic, df_plan_ASP_Export, df_Final, new_row ], ignore_index=True)
df_All

,Date,Tonase,Jenis,Breakdown
0,2022-01-31,2.746000e+06,Plan,Total Sales
1,2022-02-28,2.791200e+06,Plan,Total Sales
2,2022-03-31,2.988900e+06,Plan,Total Sales
3,2022-04-30,2.932200e+06,Plan,Total Sales
4,2022-05-31,3.100500e+06,Plan,Total Sales
...,...,...,...,...
732,2025-10-01 00:00:00,1.054503e+06,Forecast,Avg. Selling Price Export
733,2025-11-01 00:00:00,1.156312e+06,Forecast,Avg. Selling Price Export
734,2025-12-01 00:00:00,1.142294e+06,Forecast,Avg. Selling Price Export
735,2026-01-01 00:00:00,1.008743e+06,Forecast,Avg. Selling Price Export
736,2025-03-05 09:19:27.400512,0.000000e+00,Actual,Last Update

In [68]:
df_All['Date'] = pd.to_datetime(df_All['Date'])
df_All['Tonase'] = round(df_All['Tonase'], 2)

In [69]:
df_All.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 737 entries, 0 to 736
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       737 non-null    datetime64[ns]
 1   Tonase     737 non-null    float64
 2   Jenis      737 non-null    object
 3   Breakdown  737 non-null    object
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 23.2+ KB

In [52]:
import pyodbc
from dotenv import load_dotenv
import os
import pandas as pd

# Muat variabel lingkungan dari file .env
# load_dotenv()
# server = os.environ['SERVER']
# database = os.environ['DATABASE']
# username = os.environ['USERNAME_1']
# password = os.environ['PASSWORD']

# SERVER=10.3.4.139,1433
# DATABASE=dwh_prod
# USERNAME_1=developerptba
# PASSWORD=LnfPYVFW1K2TAKf
# Hardcode nilai koneksi SQL Server
server = '10.3.4.139,1433'
database = 'dwh_prod'
username = 'developerptba'
password = 'LnfPYVFW1K2TAKf'

# Koneksi ke SQL Server
try:
    # conn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
    conn = pyodbc.connect(f'DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}')
    print("Connection successful")
    
    cursor = conn.cursor() 

    # Truncate tabel
    truncate_query = "TRUNCATE TABLE dwh.DM_Sales_Forecasting"
    cursor.execute(truncate_query)
    print("Table truncated successfully.")

    # Setting fast_executemany
    cursor.fast_executemany = True

    insert_query = """
    INSERT INTO dwh.DM_Sales_Forecasting 
    ([Date], [Tonase], [Jenis], [Breakdown]) 
    VALUES (?, ?, ?, ?)
    """

    # Siapkan data yang akan di-insert
    rows_to_insert = [row for row in df_All.itertuples(index=False)]
    print(f"{len(rows_to_insert)} rows will be inserted into the database.")

    # Nonaktifkan autocommit
    conn.autocommit = False

    # Menggunakan try-except saat insert
    for row in rows_to_insert:
        cursor.execute(insert_query, row)
        
    # Commit perubahan jika semua insert berhasil
    conn.commit()
    print("Data successfully inserted.")

except Exception as e:
    print(f"An error occurred: {e}")
    if conn:
        conn.rollback()  # Rollback jika terjadi error

finally:
    cursor.close()
    conn.close()  # Pastikan koneksi selalu ditutup
    print("Connection closed.")

Connection successful
Table truncated successfully.
736 rows will be inserted into the database.
Data successfully inserted.
Connection closed.

In [70]:
# print("Sedang Import ke DM_forecast_prod_v1")

import pyodbc
from dotenv import load_dotenv
import os
import pandas as pd

# Koneksi ke SQL Server
server = '10.3.4.139,1433'
database = 'dwh_prod'
username = 'developerptba'
password = 'LnfPYVFW1K2TAKf'

# Inisialisasi koneksi ke SQL Server
try:
    conn = pyodbc.connect(
        f'DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}'
    )
    print("Koneksi ke database berhasil.")
except Exception as e:
    print(f"Error saat mencoba koneksi ke database: {e}")
    exit()

cursor = conn.cursor()

# Proses truncate tabel
truncate_query = "TRUNCATE TABLE dwh.DM_Sales_Forecasting"
try:
    cursor.execute(truncate_query)
    conn.commit()
    print("Tabel berhasil di-truncate.")
except Exception as e:
    print(f"Error saat truncate tabel: {e}")
    conn.close()
    exit()


# Pastikan `Df_Final` sudah didefinisikan
if 'df_All' not in globals():
    print("Error: DataFrame `df_All` tidak ditemukan.")
    conn.close()
    exit()

# Menyiapkan query untuk insert
insert_query = """
    INSERT INTO dwh.DM_Sales_Forecasting 
    ([Date], [Tonase], [Jenis], [Breakdown]) 
    VALUES (?, ?, ?, ?)
"""

rows_to_insert = [tuple(row) for row in df_All.itertuples(index=False)]

# Proses insert data
cursor.fast_executemany = True
try:
    cursor.executemany(insert_query, rows_to_insert)
    conn.commit()
    print(f"Berhasil Insert {len(rows_to_insert)} baris data.")
except Exception as e:
    conn.rollback()
    print(f"Error saat menginsert data: {e}")

# Menutup koneksi
cursor.close()
conn.close()
print("Forecasting Done")

Koneksi ke database berhasil.
Tabel berhasil di-truncate.
Berhasil Insert 737 baris data.
Forecasting Done

In [25]:
result_df.to_csv('df_sales.csv')